# Configuration to redirect all urls to index.html and avoid nginx 404 errors
server {
  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ @rewrites;
  }

  location @rewrites {
    rewrite ^(.+)$ /index.html last;
  }
}
